<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <Description>Standard reflection and emit helpers: DelegateHelper allows invoking virtual method base, EmitHelper and ILGeneratorExtension ease classical emit funtions.
    </Description>
  </PropertyGroup>
</Project>